language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-26
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_8b07ddf7f3da_key -iv $encrypted_8b07ddf7f3da_iv
  -in google-services.json.enc -out google-services.json -d
- chmod +x gradlew
branches:
  only:
  - master
