language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-26
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_fef2f87ed48f_key -iv $encrypted_fef2f87ed48f_iv
  -in app/google-services.json.enc -out app/google-services.json -d
- chmod +x gradlew
branches:
  only:
  - master
