language: android
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_469a66ad9dd3_key -iv $encrypted_469a66ad9dd3_iv
  -in app/google-services.json.enc -out app/google-services.json -d
- chmod +x gradlew
branches:
  only:
  - master
